### ISSUE TITLE
Snapshot check

### ISSUE THREAD

**Issue by amjelnes** [dav3860/vmbix#12]
Hi love this tool... so much better performance and flexibility than Zabbix native VMware support.

I wonder though if it would be possible to get some sort of snapshot check in there... reason for asking is that I've on occasion seen snapshots drive VM's to freeze due to lack of DS space.

Although VmBix has DS checks it'll still be great to have snapshot checks, as snapshots have a tendency to be forgotten and just lie there.

Any chance for this to be implemented?

That said... this is one of the most useful tools in my daily work!!

**Comment by ptempier** [comment]
Agreed snapshot age and snapshot size would be nice

**Comment by dav3860** [comment]
The vm.snapshot method was added to VmBix 2.4 to check if there is a snapshot.
