### ISSUE TITLE
VMware Default SSL Certificates

### ISSUE THREAD

**Issue by RubyWanKenobi** [dav3860/vmbix#18]
When I try to exexute:
vmbix -P 12050 -u username -p password -s https://vcenter.mycompany.com/sdk

I get the following exception:
Exception in thread "main" java.lang.NullPointerException
	at net.djarvur.vmbix.VmBix.main(Unknown Source)
Shutting down
Error disconnecting: null
Shutted down

I already imported rui.crt vom VCenter system into /etc/ssl/certs. Any pointers for my problem ? Thanks !

**Comment by dav3860** [comment]
You can follow http://blogs.vmware.com/developer/2014/07/getting-started-vsphere-management-sdk.html for instructions on how to add a certificate to a keystore and use the javax.net.ssl.trustStore parameter to use it.

**Comment by dav3860** [comment]
But the connection to the vCenter in VmBix ignores certificate warnings :
`new ServiceInstance(new URL(sdkUrl), uname, passwd, true);`
