### ISSUE TITLE
How to monitor multiple vcenter environments ?

### ISSUE THREAD

**Issue by blackcobra1973** [dav3860/vmbix#2]
Hello, 

I am trying to find a way to monitor multiple vcenter clusters with 1 VmBix template and vmbixd process running.  Is this possible or could this be implemented as a new feature where you provide to the vmbixd daemon the vcenter/esxi SDK url, username and password.  

I guess the sollution now is to use different templates + different vmbixd instances ? 

Thanks in advance. 

Kurt

**Comment by RubyWanKenobi** [comment]
Such a feature would be great. Right now I'm having problems to setup 2 vmbix instances + different templates. A little bit more detail about setting up multiple instances would be very useful.

**Comment by deejross** [comment]
Just throwing my two cents in here. Any decent sized company will have multiple vCenters set up. Besides the performance issues when dealing with more than a few hundred VMs, there's other considerations like environment separation (i.e. development and production). Where I work, I'd be astonished if we had fewer than 10 vCenters.

I don't know much about the VmBix design (just started looking at this to monitor datastore capacity metrics), but if it were possible, having the URLs defined as Zabbix macros (like Zabbix does for it's own VMware monitoring in 2.2+) would be the easiest from a Zabbix administration perspective. Then VmBix would pool the connections to all the different vCenters. Going through the items, it's either "yes, I've seen this URL, so I'll just reuse the existing connection I have for it", or it's "I haven't seen this URL before, so I'm going to open a new connection and add it to my pool".

**Comment by dav3860** [comment]
https://github.com/dav3860/vmbix#querying-multiple-vcenters
