### ISSUE TITLE
Problem with SSL Certificate

### ISSUE THREAD

**Issue by hexgroup** [dav3860/vmbix#20]
I have installed vmbix, but when I go to try I receive this message:
[root@vm34mz1 certs]# vmbix -P 12050 -u root -p MASKED -s https://10.1.64.130/sdk
Exception in thread "main" java.lang.NullPointerException
        at net.djarvur.vmbix.VmBix.main(Unknown Source)
Shutting down
Error disconnecting: null
Shutted down
[root@vm34mz1 certs]# vmbix -P 12050 -u root -p vmware -s https://10.1.64.130/sdk
Exception in thread "main" java.lang.NullPointerException
        at net.djarvur.vmbix.VmBix.main(Unknown Source)
Shutting down
Error disconnecting: null
Shutted down
[root@vm34mz1 certs]#
I put a ca-bundle certificate into the openssl directory but not works.
If I try with CURL it works fine:

[root@vm34mz1 certs]# curl -v -XGET https://10.1.64.130/sdk
* About to connect() to 10.1.64.130 port 443 (#0)
*   Trying 10.1.64.130... connected
* Connected to 10.1.64.130 (10.1.64.130) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_RSA_WITH_AES_256_CBC_SHA
* Server certificate:
*       subject: MASKED
*       start date: Feb 11 15:44:08 2014 GMT
*       expire date: Feb 11 15:44:08 2016 GMT
*       common name: MASKED
*       issuer: MASKED
> GET /sdk HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: 10.1.64.130
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Wed, 27 May 2015 15:51:28 GMT
< Connection: close
< Content-Type: text; charset=plain
< Content-Length: 0
<
* Closing connection #0
[root@vm34mz1 certs]#

**Comment by boyemillar** [comment]
We have the same problem... have you had any success getting past this...?

**Comment by dav3860** [comment]
Hi,
VmBix can only query the vCenter API, not an ESXi directly. I've just uploaded the version 2.0 which adds support for vSphere 6.0.
