### ISSUE TITLE
not able to query datastores or read data from previously configured datastores

### ISSUE THREAD

**Issue by WRusman** [dav3860/vmbix#21]
After upgrading to vSphere 6.0, I am unable to query datastores for information.
A manual discovery with zabbix_get returns no data for the datastores, but does return data for the other discovery options, so I assume it is not a matter of incorrect permissions on the vSphere cluster. 

zabbix_get -s 127.0.0.1 -p 12050 -k datastore.discovery[*]
{"data":[]}

zabbix_get -s 127.0.0.1 -p 12050 -k esx.discovery    {"data":[{"{#ESXHOST}":"esx1.testnet.local","{#UUID}":"32393735-3034-5a43-4a31-313030525046","{#CLUSTER}":"Testcluster"},{"{#ESXHOST}":"esx5.testnet.local","{#UUID}":"37333337-3333-5a43-4a35-303530333654","{#CLUSTER}":"Testcluster"},{"{#ESXHOST}":"esx6.testnet.local","{#UUID}":"37333337-3333-5a43-4a35-30353033364e","{#CLUSTER}":"Testcluster"},
----snip----
{"{#ESXHOST}":"esx2.testnet.local","{#UUID}":"32393735-3034-5a43-4a30-343130505650","{#CLUSTER}":"Testcluster"}]}

**Comment by dav3860** [comment]
Hi,
I've just uploaded the version 2.0 which adds support for vSphere 6.0.
