### ISSUE TITLE
What license is the code released under

### ISSUE THREAD

**Issue by fischerdr** [dav3860/vmbix#22]
Could some please let me know what license the code is under?  I had to do a fork for internal monitor project at my company and I need to ask if i can release updates and fixes.

Changes made:
1) maven pom created
2) removed ant build and ivy
3) maven package creates all in one jar
4) systemd config
5) added log-back as logging 
6) added 3 functions
     a. datastore.vm.discovery[datastore] - list virtual machines on a datastore
     b. datastore.vm.committed[datastore, virtualmachine] - space vm has committed on a datastore
     c. datastore.vm.uncommited[datastore, virtualmachine] - space vm has uncommited on a datastore

thanks

**Comment by dav3860** [comment]
Hi,
The code is under the BSD 3 license. You're welcome to release the code, thank you !
