### ISSUE TITLE
Asking for a release with the last patches

### ISSUE THREAD

**Issue by ptempier** [dav3860/vmbix#26]
Hello

Current release makes the zabbix proxy crashes repeatedly, could you please make a new release which includes the nullpointer fixe?
Since zabbix 3.0 is out i can't use the vmbix modules, and i am slightly worried about installing maven and a full build environment on the servers to compile the last git version.

**Comment by dav3860** [comment]
Hi, try the new version (2.1).

**Comment by ptempier** [comment]
Cool Cool Cool, gonna try this tomorrow.
