### ISSUE TITLE
Datastore IOPS monitoring

### ISSUE THREAD

**Issue by jovanmal** [dav3860/vmbix#31]
Hello,

I have Zabbix 3.0.3 with VmBix 2.2 installed and configured to monitor vCenter 6 with two ESX hosts. There are 3 datastores connected over FC SAN switch. 

Hosts and datastores are successfully discovered by using the **VmBix vCenter Loadable Module** template. VmBix is configured to use VMWare UUID to identify objects. 

Is there a  way to monitor latest IOPS value of datastore? I tried to use the ** **datastore.datastoreReadIops.latest** and **datastore.datastoreWriteIops.latest**  ESX counters, but getting error _Check access restrictions in Zabbix agent configuration_ 

```
[root@zabbix ~]# zabbix_get -s 127.0.0.1 -p 12050 -k "esx.counter[50673472-be243ac8-98e8-2c768a52d4fd,datastore.datastoreReadIops.latest]"
zabbix_get [93941]: Check access restrictions in Zabbix agent configuration
```

50673472-be243ac8-98e8-2c768a52d4fd is UUID of one datastore.

I got same error when used UUID of ESX host:

```
[root@zabbix ~]# zabbix_get -s 127.0.0.1 -p 12050 -k "esx.counter[32333536-3030-5a43-3232-333430325350,datastore.datastoreReadIops.latest]"
zabbix_get [92429]: Check access restrictions in Zabbix agent configuration

```

32333536-3030-5a43-3232-333430325350 is UUID of one ESX host.

Please help, what I have missed?

**Comment by dav3860** [comment]
List the instances of this performance counter using :
```
zabbix_get -s 127.0.0.1 -p 12050 -k "esx.counter.discovery[myesx01,datastore.datastoreReadIops.latest]
{
  "data": [
    {
      "{#METRICINSTANCE}": "54abdb23-2d2356f6-f002-001a4bef4838",
      "{#METRICNAME}": "DS01"
    },
    {
      "{#METRICINSTANCE}": "558ac8df-a17d83a4-4e64-a0b3cce0dcda",
      "{#METRICNAME}": "DS02"
    }
  ]
}
```
Then, you can get the counter value for each instance like this :
```
zabbix_get -s 127.0.0.1 -p 12050 -k "esx.counter[myesx01,datastore.datastoreReadIops.latest,558ac8df-a17d83a4-4e64-a0b3cce0dcda]"
0
```

**Comment by jovanmal** [comment]
Thank you very much, that worked for me. 

I successfully created item for particular datastore host (placed in Datastores host group) for example simple check key for manually created item for Datastore 3 was `vmbix[esx.counter,32333536-3030-5a43-3232-333430325350,datastore.datastoreReadIops.latest,56f7c5b3-9d9d4e5d-7ac4-2c768a536e5c]
`
Received values are going from 2 to 47 (Numeric unsigned, decimal). What this values are representing? Number of Iops?

One more question, how to create item prototype for the **datastore.datastoreReadIops.latest** counter in VmBix vCenter Loadable Module template? I tried to create item prototype named _Datastore {#DATASTORE} Read IOPS_ with simple check key 
`
vmbix[esx.counter,{32333536-3030-5a43-3232-333430325350,datastore.datastoreReadIops.latest,{#METRICINSTANCE}]`

didnt got any data, I dont know what I made wrong.

I also tried counter **disk.totalReadLatency.average**. Discovery command given me following output:

zabbix_get -s 127.0.0.1 -p 12050 -k "esx.counter.discovery[32333536-3030-5a43-3232-333430325350,disk.totalReadLatency.average]"

{
	"data":[
	{"{#METRICINSTANCE}":"naa.600c0ff00014a8563944675001000000"},
	{"{#METRICINSTANCE}":"naa.600508b1001ca821146614f1a958cdab"},
	{"{#METRICINSTANCE}":"naa.600c0ff00014f1b9f4def75601000000"},
	{"{#METRICINSTANCE}":"naa.600c0ff00014a856fe21675001000000"}]
}

What values naa.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx are meaning? Are these values some kind of UUIDs for physical disks?

I would highly appreciate any help about this.
Thank you in advance.

**Comment by dav3860** [comment]
Check here for information about the received values :
https://www.vmware.com/support/developer/converter-sdk/conv61_apireference/datastore_counters.html

For the item prototypes, create :
- a LLD discovery rule like this :
`vmbix[esx.counter.discovery,{HOST.HOST},datastore.datastoreReadIops.latest]`
- an item prototype like this :
`vmbix[esx.counter,{HOST.HOST},datastore.datastoreReadIops.latest,{#METRICINSTANCE}]`
with a name `Datastore {#METRICNAME} Read IOPS`
- another item prototype for the writes :
`vmbix[esx.counter,{HOST.HOST},datastore.datastoreWriteIops.latest,{#METRICINSTANCE}]`

For the naa.xxxx values, yes it's a VMWare ID for the disks (you can see them in the VMWare Client).

**Comment by jovanmal** [comment]
**dav3860,**  Thank you for valuable help you provided to me. Your instructions precisely conducted me to solve my doubts about VmBix counters.

Also, big THANK YOU for the outstanding piece of softvare.

Cheers,
Jovan
