### ISSUE TITLE
Large number of messages "No response from VMBIX"

### ISSUE THREAD

**Issue by jovanmal** [dav3860/vmbix#33]
[vmbix.zip](https://github.com/dav3860/vmbix/files/372886/vmbix.zip)

Hi dav3860,

I configured VmBix following your manual from the Wiki page of this project. It seemed that everything works well until I configured to get notification in case of trigger status PROBLEM.

Since then, I get the following mail every 5 minutes:
```

Subject: PROBLEM: No response from VMBIX

Trigger: No response from VMBIX
Trigger status: PROBLEM
Trigger severity: Average
Trigger URL: 

Item values:

1. VmBix Ping (vCenter:vmbix[ping]): 1
2. *UNKNOWN* (*UNKNOWN*:*UNKNOWN*): *UNKNOWN*
3. *UNKNOWN* (*UNKNOWN*:*UNKNOWN*): *UNKNOWN*

Original event ID: 8200
```

followed by another similar e-mail with subject "OK: No response from VMBIX".

I have Zabbix 3.0.3 installed on CentOS 7 x64 with VmBix 2.4.

Also, I noticed a big number of log files vmbix[date].log in the /var/log folder, each with size of 10 MB. I have the 7-8 such files per day. I attached my last vmbix.log.

In multiple graphs I see dotted line, and on several graphs sometimes there is no any data at all.

Please help

Thank you in advance

**Comment by dav3860** [comment]
Hi,
It means that VmBix didn't reply "1", or didn't reply at all during the last 5 minutes (if you didn't change the trigger). You should have a look a the vmbix.log file to see if it returns some errors.
Also check the Timeout parameter in zabbix_server.conf or zabbix_proxy.conf. By default it is set to 5s. Increase it to 15 or 20s, to see if it helps. maybe your server is overloaded and cannot handle all the requests in less than 5s.

**Comment by jovanmal** [comment]
Thank you for quick answer dav3860.

CPUs was quite overloaded, so added one more virtual CPU - there are 3 cores now. VM has 2 GB of RAM, 50% used - I think that is not necessary to increase it for now.

Also changed parameters **StartPollers** on 50 (default was 5) and **StartPingers** on 7 (default was 1)

After that, it seems to have resolved this problem.

Thank you for big help ;)
