### ISSUE TITLE
Not able to query datastores from ESXi 5.5

### ISSUE THREAD

**Issue by Gwynnbleid1** [dav3860/vmbix#34]
Hi

I am unable to query datastores for information. All symptoms are exactly the same as described in issue  #21. The only diffrence is ESXi version. 

PS. Can somebody help me with other issue posted here: [https://github.com/dav3860/vmbix_zabbix_module/issues/6](url)

**Comment by dav3860** [comment]
Hi,
What version of VmBix do you use ? What kind of datastore do you have ? What are the exact symptoms ?

**Comment by dav3860** [comment]
Could you also enable debug with in the file /etc/vmbix/logback.xml :
```
[...]
  <root level="debug">
    <appender-ref ref="FILE" />
  </root>
</configuration>
```
and restart the vmbixd daemon. Then paste the output of /var/log/vmbix.log when you reproduce the issue.
