### ISSUE TITLE
Cant view Guest VM count per Host 

### ISSUE THREAD

**Issue by boyemillar** [dav3860/vmbix#42]
I've added a new Item to the template to get the number of VMs on each host but i cant get it to work. All the other standard Items data in the templates return fine from our Zabbix Proxy where vmbix is installed.

I've tried both... 

esx.vms.count[HOST.HOST]
vmbix[esx.vms.count,{HOST.HOST}]

If i run the first command above from the zabbix proxy server it returns fine

zabbix_get -s 127.0.0.1 -p 12050 -k esx.vms.count[MY-ESXiHOST.fqdn]

**Comment by dav3860** [comment]
Please enable debug on VmBix, reproduce the issue, and post the results.
