### ISSUE TITLE
Some items vmbix don't return value after update Zabbix-server

### ISSUE THREAD

**Issue by ZabbixUser** [dav3860/vmbix#52]
## Version:
Zabbix-server 3.4.6
Vmbix 2.6.0.172

## Issue
I update Zabbix-server 3.4.5 to 3.4.6 and many items in "Template VmBix VM Loadable Module" don't return any value and wait in Zabbix-server queue after this update.

Items who don't return value: 
- Discovery rule CPU
- Discovery rule vDisk

- Network Rx (bits/s)
- Network Tx (bits/s)

Other items in the template work correctly.

In Vmbix log only this appear: 
`vm.guest.tools.status[VM]' not supported`
The command: _zabbix_get -s 127.0.0.1 -p 12050 -k "vmbix.version"_ work !
I restart services and hosts but nothing change.

Any ideas for this issue ?

**Comment by ZabbixUser** [comment]
## More informations
Only "counter" request don't return value:
`zabbix_get -s 127.0.0.1 -p 12050 -k "vm.counter[(#UUID)]"`
ZBX_NOTSUPPORTED

**Comment by ZabbixUser** [comment]
## With Zabbix-agent 
With zabbix-agentd version command don't work too.
```
#zabbix_agentd -t vmbix[version]
zabbix_agentd [26254]: VmBix module version 1.1
zabbix_agentd [26254]: Loading VmBix module configuration file /etc/zabbix/vmbix_module.conf
vmbix[version]                                [s|ZBX_NOTSUPPORTED]

```

**Comment by dav3860** [comment]
Thanks for reporting this. I'm going to check this in my lab.

**Comment by ZabbixUser** [comment]
Hi dav3860,

Thanks for your time, today for unknow reason after 28 days of inactivity; the Vmbix module work correctly ! I didn't change anything I just view in log at the moment of recovery `" item "VM1:<discovery-item>[{HOST.HOST}]" became supported".`

I'm curious to know what's happen.

Thanks again.
