### ISSUE TITLE
Zabbix v4.2.1 Not working

### ISSUE THREAD

**Issue by boyemillar** [dav3860/vmbix#56]
v4.2.0 worked fine however since updating to v4.2.1 i dont get any data returned from VMBIX

**Comment by dav3860** [comment]
This issue is not related to the version of Zabbix. It's just that VMBix cannot connect to the VMWare API.

**Comment by boyemillar** [comment]
Hi.... Thanks for the fast response. :)

This was working fine but as soon as i updated all 4 of my VMBIX proxies are pulling data back from our separate VCenters. I have the same credentials on all 4 VCenters and the domain account we use looks fine. Do you have any ideas of other things i can try.

**Comment by whosgonna** [comment]
For isolation purposes, do you have any other software that utilizes the vcenter sdk?


Is this line a part of the response when you run a zabbix_get request, or is it the command you are running:

```vmbix -P 12050 -u "mydomain\myaccount" -p "mypassword" -s "https://myip:443/sdk"```

It probably won't make a difference, but you could also try formatting the username as user@domain.com

**Comment by boyemillar** [comment]
Sorry @dav3860 finger trouble from me wrong IP used for the manual check above during the panic... However none of my Proxies are pulling data since the upgrade about 1 hour ago. Zabbix_get command is able to pull individual data...

# zabbix_get -s 127.0.0.1 -p 12050 -k about[*]
returns the following = VMware vCenter Server 6.0.0 build-3634793

**Comment by whosgonna** [comment]
Is there anything in the zabbix proxy log regarding the vmbix pluggable module?

I don't know if there's a pre compiled module for 4.2, but you could manually compile it

**Comment by boyemillar** [comment]
Hi @whosgonna 
The line you have referred to is the command i ran but in the "myip" part i had put the ip of the proxy instead of the VCenter my bad... I'm just wondering why i cant get the info back via vmbixd the zabbix_get command is working as a test.

**Comment by boyemillar** [comment]
I tested the previously released module a few weeks ago on v4.2 and it was working fine. Maybe they have changed something which means a recompile will now be required. 

Yep ther is an issue with the loadable module zabbix proxy log is showing this...

 10462:20190424:135102.674 Starting Zabbix Proxy (active) [ZBX_TRAKSVRVC]. Zabbix 4.2.1 (revision 92832).
 10462:20190424:135102.674 **** Enabled features ****
 10462:20190424:135102.674 SNMP monitoring:       YES
 10462:20190424:135102.674 IPMI monitoring:       YES
 10462:20190424:135102.674 Web monitoring:        YES
 10462:20190424:135102.674 VMware monitoring:     YES
 10462:20190424:135102.674 ODBC:                  YES
 10462:20190424:135102.674 SSH2 support:          YES
 10462:20190424:135102.675 IPv6 support:          YES
 10462:20190424:135102.675 TLS support:           YES
 10462:20190424:135102.675 **************************
 10462:20190424:135102.675 using configuration file: /etc/zabbix/zabbix_proxy.conf
 10462:20190424:135102.675 cannot load module "vmbix.so": /usr/lib/zabbix/modules/vmbix.so: undefined symbol: __zbx_zbx_dsprintf
 10462:20190424:135102.675 loading modules failed, exiting...

**Comment by whosgonna** [comment]
Are you able to manually recompile the module?  Its fairly straightforward
following the instructions in the module documentation.

**Comment by boyemillar** [comment]
I'll need to do this on a separate box... I'll give it a try tonight and let you know if it works.

**Comment by boyemillar** [comment]
Hi @whosgonna & @dav3860...

A recompile of the vmbix.so file usng the v4.2.1 source files has done the trick all working fine now.

Thanks for your help and apologies for the initial mixup with my IP mistake.

**Comment by boyemillar** [comment]
Issue now closed
